[2023-03-21T12:47:54.971+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables manual__2023-03-21T12:47:20.072089+00:00 [queued]>
[2023-03-21T12:47:55.137+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables manual__2023-03-21T12:47:20.072089+00:00 [queued]>
[2023-03-21T12:47:55.143+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T12:47:55.153+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-21T12:47:55.156+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T12:47:55.262+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_database_tables> on 2023-03-21 12:47:20.072089+00:00
[2023-03-21T12:47:55.359+0000] {standard_task_runner.py:55} INFO - Started process 455 to run task
[2023-03-21T12:47:55.408+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'batch_pipeline', 'extract_database_tables', 'manual__2023-03-21T12:47:20.072089+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/load_csv.py', '--cfg-path', '/tmp/tmp09056tm8']
[2023-03-21T12:47:55.414+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask extract_database_tables
[2023-03-21T12:47:55.956+0000] {task_command.py:388} INFO - Running <TaskInstance: batch_pipeline.extract_database_tables manual__2023-03-21T12:47:20.072089+00:00 [running]> on host 070f7bf9e1a1
[2023-03-21T12:47:56.365+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pedrosa
AIRFLOW_CTX_DAG_ID=batch_pipeline
AIRFLOW_CTX_TASK_ID=extract_database_tables
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T12:47:20.072089+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T12:47:20.072089+00:00
[2023-03-21T12:47:56.851+0000] {logging_mixin.py:137} INFO - Erro: (psycopg2.OperationalError) connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-03-21T12:47:56.865+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-21T12:47:56.913+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=batch_pipeline, task_id=extract_database_tables, execution_date=20230321T124720, start_date=20230321T124754, end_date=20230321T124756
[2023-03-21T12:47:56.999+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-21T12:47:57.138+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
