[2023-03-22T04:41:25.799+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_json_to_postgres.extract_csv_files scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T04:41:26.339+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_json_to_postgres.extract_csv_files scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T04:41:26.363+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T04:41:26.415+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-22T04:41:26.419+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T04:41:26.610+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_csv_files> on 2023-03-21 00:00:00+00:00
[2023-03-22T04:41:26.689+0000] {standard_task_runner.py:55} INFO - Started process 2359 to run task
[2023-03-22T04:41:26.777+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_json_to_postgres', 'extract_csv_files', 'scheduled__2023-03-21T00:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/***_etl.py', '--cfg-path', '/tmp/tmplb0igll2']
[2023-03-22T04:41:26.787+0000] {standard_task_runner.py:83} INFO - Job 197: Subtask extract_csv_files
[2023-03-22T04:41:27.629+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_json_to_postgres.extract_csv_files scheduled__2023-03-21T00:00:00+00:00 [running]> on host 070f7bf9e1a1
[2023-03-22T04:41:28.547+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sanvi
AIRFLOW_CTX_DAG_ID=csv_json_to_postgres
AIRFLOW_CTX_TASK_ID=extract_csv_files
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T00:00:00+00:00
[2023-03-22T04:41:28.628+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_etl.py", line 27, in extract_csv_files
    df1 = pd.read_csv('airflow-fp/dags/data/precipitation.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'airflow-fp/dags/data/precipitation.csv'
[2023-03-22T04:41:29.014+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_json_to_postgres, task_id=extract_csv_files, execution_date=20230321T000000, start_date=20230322T044126, end_date=20230322T044128
[2023-03-22T04:41:29.204+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 197 for task extract_csv_files ([Errno 2] No such file or directory: 'airflow-fp/dags/data/precipitation.csv'; 2359)
[2023-03-22T04:41:29.360+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T04:41:29.707+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
