[2023-03-22T05:06:24.703+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres.extract_data manual__2023-03-22T05:06:17.293773+00:00 [queued]>
[2023-03-22T05:06:24.729+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres.extract_data manual__2023-03-22T05:06:17.293773+00:00 [queued]>
[2023-03-22T05:06:24.732+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T05:06:24.735+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-22T05:06:24.740+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T05:06:24.788+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-22 05:06:17.293773+00:00
[2023-03-22T05:06:24.802+0000] {standard_task_runner.py:55} INFO - Started process 2758 to run task
[2023-03-22T05:06:24.819+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres', 'extract_data', 'manual__2023-03-22T05:06:17.293773+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/etl_climate.py', '--cfg-path', '/tmp/tmplxahr3k9']
[2023-03-22T05:06:24.822+0000] {standard_task_runner.py:83} INFO - Job 201: Subtask extract_data
[2023-03-22T05:06:24.975+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_to_postgres.extract_data manual__2023-03-22T05:06:17.293773+00:00 [running]> on host 070f7bf9e1a1
[2023-03-22T05:06:25.136+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sanvi
AIRFLOW_CTX_DAG_ID=csv_to_postgres
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T05:06:17.293773+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T05:06:17.293773+00:00
[2023-03-22T05:06:29.002+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_climate.py", line 28, in extract_data
    df1 = pd.read_csv(url_1)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 27, saw 367

[2023-03-22T05:06:29.025+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=csv_to_postgres, task_id=extract_data, execution_date=20230322T050617, start_date=20230322T050624, end_date=20230322T050629
[2023-03-22T05:06:29.051+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 201 for task extract_data (Error tokenizing data. C error: Expected 1 fields in line 27, saw 367
; 2758)
[2023-03-22T05:06:29.109+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T05:06:29.165+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
