[2023-03-21T13:36:01.086+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-03-21T13:36:01.147+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-03-21T13:36:01.149+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T13:36:01.151+0000] {taskinstance.py:1283} INFO - Starting attempt 10 of 10
[2023-03-21T13:36:01.153+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T13:36:01.211+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_database_tables> on 2023-03-20 00:00:00+00:00
[2023-03-21T13:36:01.248+0000] {standard_task_runner.py:55} INFO - Started process 1434 to run task
[2023-03-21T13:36:01.270+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'batch_pipeline', 'extract_database_tables', 'scheduled__2023-03-20T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/load_csv.py', '--cfg-path', '/tmp/tmp1ifougc1']
[2023-03-21T13:36:01.274+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask extract_database_tables
[2023-03-21T13:36:01.610+0000] {task_command.py:388} INFO - Running <TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-20T00:00:00+00:00 [running]> on host 070f7bf9e1a1
[2023-03-21T13:36:01.871+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pedrosa
AIRFLOW_CTX_DAG_ID=batch_pipeline
AIRFLOW_CTX_TASK_ID=extract_database_tables
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-20T00:00:00+00:00
[2023-03-21T13:36:01.947+0000] {logging_mixin.py:137} INFO - Erro: (psycopg2.OperationalError) connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-03-21T13:36:01.949+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-21T13:36:01.992+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=batch_pipeline, task_id=extract_database_tables, execution_date=20230320T000000, start_date=20230321T133601, end_date=20230321T133601
[2023-03-21T13:36:02.087+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-21T13:36:02.189+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
