[2023-03-22T04:46:37.242+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_json_to_postgres.extract_json_files scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T04:46:37.283+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_json_to_postgres.extract_json_files scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T04:46:37.286+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T04:46:37.289+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-03-22T04:46:37.291+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T04:46:37.361+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_json_files> on 2023-03-21 00:00:00+00:00
[2023-03-22T04:46:37.376+0000] {standard_task_runner.py:55} INFO - Started process 2444 to run task
[2023-03-22T04:46:37.398+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_json_to_postgres', 'extract_json_files', 'scheduled__2023-03-21T00:00:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/***_etl.py', '--cfg-path', '/tmp/tmp_00hqm2y']
[2023-03-22T04:46:37.408+0000] {standard_task_runner.py:83} INFO - Job 200: Subtask extract_json_files
[2023-03-22T04:46:37.704+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_json_to_postgres.extract_json_files scheduled__2023-03-21T00:00:00+00:00 [running]> on host 070f7bf9e1a1
[2023-03-22T04:46:37.992+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sanvi
AIRFLOW_CTX_DAG_ID=csv_json_to_postgres
AIRFLOW_CTX_TASK_ID=extract_json_files
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T00:00:00+00:00
[2023-03-22T04:46:38.008+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_etl.py", line 35, in extract_json_files
    with open(f'airflow-fp/data/json/yelp_academic_dataset_business1.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'airflow-fp/data/json/yelp_academic_dataset_business1.json'
[2023-03-22T04:46:38.052+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=csv_json_to_postgres, task_id=extract_json_files, execution_date=20230321T000000, start_date=20230322T044637, end_date=20230322T044638
[2023-03-22T04:46:38.298+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 200 for task extract_json_files ([Errno 2] No such file or directory: 'airflow-fp/data/json/yelp_academic_dataset_business1.json'; 2444)
[2023-03-22T04:46:38.385+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T04:46:38.556+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
