[2023-03-22T01:34:25.365+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T01:34:25.396+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T01:34:25.399+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T01:34:25.401+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-03-22T01:34:25.403+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T01:34:25.436+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_database_tables> on 2023-03-21 00:00:00+00:00
[2023-03-22T01:34:25.449+0000] {standard_task_runner.py:55} INFO - Started process 279 to run task
[2023-03-22T01:34:25.461+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'batch_pipeline', 'extract_database_tables', 'scheduled__2023-03-21T00:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/batch_pipeline.py', '--cfg-path', '/tmp/tmpedy_0eqp']
[2023-03-22T01:34:25.465+0000] {standard_task_runner.py:83} INFO - Job 174: Subtask extract_database_tables
[2023-03-22T01:34:25.631+0000] {task_command.py:388} INFO - Running <TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-21T00:00:00+00:00 [running]> on host 070f7bf9e1a1
[2023-03-22T01:34:25.758+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pedrosa
AIRFLOW_CTX_DAG_ID=batch_pipeline
AIRFLOW_CTX_TASK_ID=extract_database_tables
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T00:00:00+00:00
[2023-03-22T01:34:25.790+0000] {logging_mixin.py:137} INFO - Erro: (psycopg2.errors.UndefinedTable) relation "categories" does not exist
LINE 1: select * from categories;
                      ^

[SQL: select * from categories;]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-03-22T01:34:25.791+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-22T01:34:25.815+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=batch_pipeline, task_id=extract_database_tables, execution_date=20230321T000000, start_date=20230322T013425, end_date=20230322T013425
[2023-03-22T01:34:25.883+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-22T01:34:25.938+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-03-22T02:45:53.429+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T02:45:53.451+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T02:45:53.453+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T02:45:53.456+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-03-22T02:45:53.458+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T02:45:53.489+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_database_tables> on 2023-03-21 00:00:00+00:00
[2023-03-22T02:45:53.501+0000] {standard_task_runner.py:55} INFO - Started process 492 to run task
[2023-03-22T02:45:53.519+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'batch_pipeline', 'extract_database_tables', 'scheduled__2023-03-21T00:00:00+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/batch_pipeline.py', '--cfg-path', '/tmp/tmp_ahk_v98']
[2023-03-22T02:45:53.523+0000] {standard_task_runner.py:83} INFO - Job 195: Subtask extract_database_tables
[2023-03-22T02:45:53.748+0000] {task_command.py:388} INFO - Running <TaskInstance: batch_pipeline.extract_database_tables scheduled__2023-03-21T00:00:00+00:00 [running]> on host 070f7bf9e1a1
[2023-03-22T02:45:53.919+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pedrosa
AIRFLOW_CTX_DAG_ID=batch_pipeline
AIRFLOW_CTX_TASK_ID=extract_database_tables
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T00:00:00+00:00
[2023-03-22T02:45:53.945+0000] {logging_mixin.py:137} INFO - Erro: (psycopg2.errors.UndefinedTable) relation "categories" does not exist
LINE 1: select * from categories;
                      ^

[SQL: select * from categories;]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-03-22T02:45:53.947+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-22T02:45:53.972+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=batch_pipeline, task_id=extract_database_tables, execution_date=20230321T000000, start_date=20230322T024553, end_date=20230322T024553
[2023-03-22T02:45:54.065+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-22T02:45:54.124+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
